FROM ubuntu:latest

RUN apt-get update -y && \
    apt-get full-upgrade -y

RUN apt-get install -y \
    sudo \
    python3 \
    python3-pip \
    ruby-full \ 
    libtool \
    libffi-dev \
    ruby-dev \
    libzmq3-dev

# RUN rm -rf /var/lib/apt/lists/*

# RUN useradd -m -s /bin/bash juser
# RUN usermod -aG sudo juser
# RUN echo 'juser:pass' | chpasswd

# USER juser
# WORKDIR /home/juser

# RUN pip3 install --user \
RUN pip3 install \
    jupyterlab \
    jupyter-console \
    --break-system-packages

# RUN gem install --user-install \
#     # ffi-rzmq \
#     iruby

# RUN iruby register --force